theme: jekyll-theme-minimal
title: Hello 👋, Darrin here.
profile: https://avatars2.githubusercontent.com/u/6406509?s=460&u=659d846a090f01b5ab4b6a9885ab070116215015&v=4
show_cv: true
cv_dl_link: https://tinyurl.com/y5ukcyqq
