theme: jekyll-theme-minimal
title: Darrin's Personal Summary
description: Things I did that I think are interesting
logo: https://avatars2.githubusercontent.com/u/6406509?s=460&u=659d846a090f01b5ab4b6a9885ab070116215015&v=4
